#!/bin/bash

# Actual functions

setup() {
  if [ -z $filename -a -z $directory ]; then
    echo "You must give both the filename and directory."
    exit 1
  else
    read -p "The script named $filename will be made in the directory $directory. Is this correct (Y/n) " userinput
    case $userinput in
      Y|y) echo "Proceeding..."; ;;
      N|n)
        echo "Aborting..."
        exit 0
        ;;
      *) echo "Unknown input."; exit 1;;
    esac
    
    echo "Creating script..."
    cd $directory
    filename+=".sh"
    touch $filename
    echo "Setting script up..."
    chmod +x $filename
    echo "#!/bin/bash" > $filename
    if [ -e $filename ]; then
      echo "File has successfully been made and setup!"
      exit 0
    else
      echo "File has failed to be made."
      exit 1
    fi
  fi
}

## Usage variable
usage=" bashutil [OPTION]...

        Warning: Files will be made in the ~ directory.

        Options:

"

ver="
Version 1.6
"

# Check if there is no input given
if [ $# = 0 ]; then
  echo "One option must be given."
  printf '%s\n' "$usage"
  exit 1
fi

# Get options
while getopts "hvf:d:" optgiven; do
  case $optgiven in
    h)
      printf '%s\n' "$usage"
      exit 0
      ;;
    v)
      printf '%s\n' "$ver"
      exit 0
      ;;
    f)
      filename=$OPTARG
      ;;
    d) 
      directory=$OPTARG
      ;;
    esac
done
setup
