#!/bin/bash

# Actual functions

function setup () {
        cd ~
        echo "Input the filename without any extension."
        read FILE
	FILE+=".sh"
        touch $FILE
        echo "#!/bin/bash" > $FILE
	chmod +x $FILE
	[ -x "$FILE" ] && echo "File successfully made."; exit 0
	[ ! -x "$FILE" ] && echo "File wasn't made due to error."; exit 1
}

# Handles options and arguments

## Usage variable
usage=" bashutil [OPTION]...

        Warning: Files will be made in the ~ directory.

        Options:

		-h or --help: Shows this screen.
		-v or --version: Shows current version.
		-s or --setup: Creates and sets up a bash script
"

## Latest Version getter
function getlatestver () {
	latestver=$(curl https://raw.githubusercontent.com/0xBooper/BashScriptingUtility/primary/currentver)
}


## Version:
ver="
Version 1.5.3

Latest Version: $latestver
"

[ -z "$1" ] && echo "You must have atleast 1 option. Run bashutil --help for info."

case "$1" in
	-h|--help) printf '%s\n' "$usage"; exit 0;;
	-v|--version) getlatestver && printf '%s\n' "$ver"; exit 0;;
	-s|--setup) setup;;
	*) echo "Unknown option."; exit 1;;
esac
